//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book_Master()
        {
            this.Book_Register_Sub = new HashSet<Book_Register_Sub>();
            this.Purchase_Sub = new HashSet<Purchase_Sub>();
        }
    
        public string Book_Id { get; set; }
        public string Book_Name { get; set; }
        public string Book_Auth { get; set; }
        public string Book_Edition { get; set; }
        public string Book_Publish { get; set; }
        public string Sr_Id { get; set; }
        public string Book_Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Book_Register_Sub> Book_Register_Sub { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase_Sub> Purchase_Sub { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
