//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book_Register_Main
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book_Register_Main()
        {
            this.Book_Register_Sub = new HashSet<Book_Register_Sub>();
        }
    
        public string Reg_Id { get; set; }
        public string Reg_Date { get; set; }
        public string Mem_id { get; set; }
        public string Reg_Status { get; set; }
    
        public virtual Member_Master Member_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Book_Register_Sub> Book_Register_Sub { get; set; }
    }
}
