//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book_Register_Sub
    {
        public string Reg_Id { get; set; }
        public string Reg_Date { get; set; }
        public string Mem_Id { get; set; }
        public string Brs_No { get; set; }
        public string Book_Id { get; set; }
        public string BrOutDate { get; set; }
        public string BrInDate { get; set; }
        public string Br_Qty { get; set; }
        public string Br_Fine { get; set; }
        public string Br_Status { get; set; }
    
        public virtual Book_Master Book_Master { get; set; }
        public virtual Book_Register_Main Book_Register_Main { get; set; }
        public virtual Member_Master Member_Master { get; set; }
    }
}
