//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LMSEntities : DbContext
    {
        public LMSEntities()
            : base("name=LMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Book_Master> Book_Master { get; set; }
        public virtual DbSet<Book_Register_Main> Book_Register_Main { get; set; }
        public virtual DbSet<Book_Register_Sub> Book_Register_Sub { get; set; }
        public virtual DbSet<LogIn> LogIns { get; set; }
        public virtual DbSet<Mem_Transaction> Mem_Transaction { get; set; }
        public virtual DbSet<Member_Master> Member_Master { get; set; }
        public virtual DbSet<Plan_Master> Plan_Master { get; set; }
        public virtual DbSet<Purchase_Main> Purchase_Main { get; set; }
        public virtual DbSet<Purchase_Sub> Purchase_Sub { get; set; }
        public virtual DbSet<Rack_Master> Rack_Master { get; set; }
        public virtual DbSet<Role_Master> Role_Master { get; set; }
        public virtual DbSet<Sec_Rac_Map> Sec_Rac_Map { get; set; }
        public virtual DbSet<Section_Master> Section_Master { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
    }
}
