//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mem_Transaction
    {
        public string Trans_Id { get; set; }
        public string Trans_Date { get; set; }
        public string Mem_Id { get; set; }
        public string Mem_Name { get; set; }
        public string Amount { get; set; }
        public string Fine { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
    
        public virtual Member_Master Member_Master { get; set; }
    }
}
