//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sec_Rac_Map
    {
        public string Sr_ID { get; set; }
        public string Sec_ID { get; set; }
        public string Rack_ID { get; set; }
        public string Sr_Status { get; set; }
    
        public virtual Rack_Master Rack_Master { get; set; }
        public virtual Section_Master Section_Master { get; set; }
    }
}
