//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public string Book_Id { get; set; }
        public string Book_Name { get; set; }
        public string Qty { get; set; }
        public string Status { get; set; }
    
        public virtual Book_Master Book_Master { get; set; }
    }
}
